skillMetadata:
  sections:
    - name: Add new script
      fields:
        - name: new_name
          type: text
          label: Name
          value: ""
        - name: new_triggers
          type: text
          label: Triggers
          value: ""
        - name: new_commands
          type: text
          label: Commands
          value: ""
